### ISSUE TITLE
NewtifryPro v 2.2.2

### ISSUE THREAD

**Issue by didjoss** [thunderace/NewtifryPro-node#1]
Bonjour,
l'envoie d'image par newtifryPro-node ne fonctionne pas avec newtifryPro v 2.2.2 alors que celui-ci reçoit bien des images de test (avec l'appli) . Le message est bien reçu mais pour les images, il y a le message "erreur de téléchargement"
Il faut bien ne mettre que l'url de l'image dans les champs image1..4 de message.data ?
Didier.

**Comment by thunderace** [comment]
Bonjour,
Il faut que le lien vers l'image soit en https, les liens en http sont refusés par la librairie standard Android.
Je vais regarder si je peux améliorer ça.
